import {
  ClerkProvider,
} from "@clerk/nextjs";
import "./globals.css";


export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <ClerkProvider>{children}</ClerkProvider>
      </body>
    </html>
  );
}
